mkdir a:\low
mkdir a:\iopl
copy *.cpp a:
copy *.c a:
copy *.h a:
copy *.rc a:
copy low\*.cpp a:\low
copy low\*.c a:\low
copy low\*.h a:\low
copy iopl\*.cpp a:\iopl
copy iopl\*.c a:\iopl
copy iopl\*.asm a:\iopl
copy iopl\*.h a:\iopl
copy iopl\*.lib a:\iopl
copy hiltner.prj a:
copy mcgraw.prj a:
copy backit.bat a:
copy iopl\*.prj a:\iopl
copy point* a:
copy *.dlg a:
copy *.tcs a:
copy *.def a:
copy *.res a:
copy *.dll a:
