
#define ID_APPNAME                     1
// menu constants
#define IDM_THREADS                  100
#define IDM_MOVE                101
#define IDM_MOVERADEC            111
#define IDM_MOVEDOME         112
#define IDM_ALLSTOP           102
#define IDM_ARRANGE           103
#define IDM_ABSMOVE                  110
#define IDM_ABOUT                    104
#define IDM_PAUSE						105
#define IDM_TRACK            120
#define IDM_TRACK1         121
#define IDM_TRACK2           122
#define IDM_TRACK3                  123
#define IDM_TRACK4                    124
#define IDM_FOCUSFWD					130
#define IDM_FOCUSREV					131
#define IDM_DOMEFWD						132
#define IDM_DOMEREV						133
#define IDM_DOMESTOP					134
#define IDM_TIME_STR                401
#define IDM_TIME                    402
#define IDM_FRAME2                  400

// Dialog Constants...
#define	IDD_DISPDLG		400
#define	IDD_DISPLAY		1
#define IDD_TIME_STR	402
#define IDD_TIME		403

#define IDD_FRAME                   401
#define IDD_SIDREAL_STR             404
#define IDD_UNIVERSAL_STR           406
#define IDD_RA_STR                  408
#define IDD_RA	409
#define IDD_DEC_STR                 410
#define IDD_DEC                     411
#define IDD_DOME_STR                412
#define IDD_DOME                    413
#define IDD_FOCUS_STR               414
#define IDD_FOCUS                   415
#define IDD_NORTH_STR               416
#define IDD_NORTH                   417
#define IDD_SOUTH_STR               418
#define IDD_SOUTH                   419
#define IDD_EAST_STR                420
#define IDD_EAST                    421
#define IDD_WEST_STR                422
#define IDD_WEST                    423
#define IDD_FOCUSIN_STR             424
#define IDD_FOCUSIN                 425
#define IDD_FOCUSOUT_STR            426
#define IDD_FOCUSOUT                427
#define IDD_SLEW_STR                428
#define IDD_SLEW                    429
#define IDD_GUIDESET_STR            430
#define IDD_GUIDESET                431
#define IDD_DRIVES_STR              432
#define IDD_DRIVES                  433
#define IDD_GUIDER_STR              434
#define IDD_GUIDER                  435
#define IDD_TRACKING_STR            436
#define IDD_TRACKING                437
#define IDD_AUTODOME_STR            438
#define IDD_AUTODOME                439
#define IDD_SIDE_HR                 405
#define IDD_SIDE_MIN                407
#define IDD_SIDE_SEC								442
#define IDD_TIME_HR                 500
#define IDD_TIME_MIN                501

#define IDD_TIME_SEC								502

#define IDD_UNIV_HR                 503
#define IDD_UNIV_MIN                504

#define IDD_UNIV_SEC								505
#define IDD_LOCAL_HR                 500
#define IDD_LOCAL_MIN                501

#define IDD_LOCAL_SEC								502
#define IDD_ROTATOR_STR							509
#define IDD_ROTATOR									510

